README.md

Updating instructions for adapter workflow in README.md

UPDATE: Updating README.md

---

README.md

[HTP-0000] Update README.md

---

trust-x/CHANGES.md
trust-x/DOCUMENTATION.md
trust-x/trust-x-htb-exports.js
trust-x/trust-x-htb-system-tests.js
trust-x/trust-x-htb-validator.js
trust-x/trust-x-htb.js

Migrate in new repo. Update doc file. Use globalTimeout as wtimeout value.
Previous pull request - https://github.com/indexexchange/trust-x-adapter/pull/8

[HTP-0001] TrustX Adapter: migrate in new repo

---

b-real-time/DOCUMENTATION.md
b-real-time/b-real-time-htb-exports.js
b-real-time/b-real-time-htb-validator.js
b-real-time/b-real-time-htb.js

Migrating bRealTime into ht-wrapper-adapters.

bRealTime: Migrating Adapter

---

trust-x/CHANGES.md
trust-x/DOCUMENTATION.md
trust-x/trust-x-htb-exports.js
trust-x/trust-x-htb-system-tests.js
trust-x/trust-x-htb-validator.js
trust-x/trust-x-htb.js

Adding TrustX adapter into master

[HTP-0001] TrustX: Adding TrustX adapter into master

---

beachfront/CHANGES.md
beachfront/DOCUMENTATION.md
beachfront/beachfront-htb-exports.js
beachfront/beachfront-htb-system-tests.js
beachfront/beachfront-htb-validator.js
beachfront/beachfront-htb.js

Beachfront: Migrating Adapter

---

locker-dome/DOCUMENTATION.md
locker-dome/locker-dome-htb-exports.js
locker-dome/locker-dome-htb-system-tests.js
locker-dome/locker-dome-htb-validator.js
locker-dome/locker-dome-htb.js

Migrating LockerDome to ht-wrapper-adapter

LockerDome: Migrating Adapter

---

.eslintignore
optimera/CHANGES.md
optimera/DOCUMENTATION.md
optimera/optimera-htb-exports.js
optimera/optimera-htb-system-tests.js
optimera/optimera-htb-validator.js
optimera/optimera-htb.js

- [ x ] Code Refactor
Updating to new IX Process

Moving Optimera to new repo.

---

README.md

Updated references to IX Library

---

.eslintignore
optimera/CHANGES.md
optimera/DOCUMENTATION.md
optimera/optimera-htb-exports.js
optimera/optimera-htb-system-tests.js
optimera/optimera-htb-validator.js
optimera/optimera-htb.js

- [x ] Feature Update
Basing off of the master branch instead of canary
https://github.com/indexexchange/ht-wrapper-adapters/pull/45
#

[HTP-0001] Optimera Adapter: Moving to new repo

---

yoc/CHANGES.md
yoc/DOCUMENTATION.md
yoc/yoc-htb-exports.js
yoc/yoc-htb-system-tests.js
yoc/yoc-htb-validator.js
yoc/yoc-htb.js

Initial version - implementation of YOC's VIS.X bidder. In case of questions, please reach out to vladimir.miliushin@yoc.com or evgenij.tovba@yoc.com.

YOC: Initial version, implemented YOC's VIS.X bidder

---

package-lock.json

WIP: ADS update

---

yoc/yoc-htb.js

ESLint complained about comment formatting.
#

YOC: fix eslint errors

---

package-lock.json

Updated base-adapter-template version to latest

Updated base-adapter-template version to latest

---

rtk/CHANGES.md
rtk/DOCUMENTATION.md
rtk/rtk-htb-exports.js
rtk/rtk-htb-system-tests.js
rtk/rtk-htb-validator.js
rtk/rtk-htb.js

- Add publisher defined categories
- Add width & height params
- PageURL instead of Hostname for rtkreferer
- gdpr true/false instead of 1/0
- Fix eslint
- Fix system tests

[HTP-0001] rtk-adapter: Read publisher defined categories

---

package-lock.json

This includes YOC's lint fixes and ADS/template updates.

Merge master into canary

---

yoc/DOCUMENTATION.md

Updating documentation to reflect our current support of the SafeFrames.

[HTP-91] YOC - Adapter Update - SafeFrame Support documentation

---

beachfront/CHANGES.md
beachfront/beachfront-htb-system-tests.js
beachfront/beachfront-htb.js

Adds support to pass the Unified ID in the bid request.

[HTP-66] Beachfront: Unified ID Support

---

pub-matic/DOCUMENTATION.md
pub-matic/pub-matic-htb-exports.js
pub-matic/pub-matic-htb-system-tests.js
pub-matic/pub-matic-htb-validator.js
pub-matic/pub-matic-htb.js

As chrome will only send third-party cookies over secure connections, pubmatic will make all requests over https.Also secure flag will be set to 1
Earlier in ortb request to PubMatic's endpoint we were passing eids as object which was an issue. Resolved this issue by converting eids from object to Array

HTP-78 PubMatic : Changing protocol to HTTPS 

---

gum-gum/CHANGES.md
gum-gum/DOCUMENTATION.md
gum-gum/gum-gum-htb-exports.js
gum-gum/gum-gum-htb-system-tests.js
gum-gum/gum-gum-htb-validator.js
gum-gum/gum-gum-htb.js

Migrates to new IX repo. adds a ns param and stringifies jcsi
[Previous PR](https://github.com/indexexchange/gum-gum-adapter/pull/10)

GumGum: Migrate to new IX repo

---

optimera/CHANGES.md
optimera/optimera-htb-system-tests.js
optimera/optimera-htb.js

- [ x ] Bug Fix
Updating the network request to point to CloudFront, and switched to using getPathName() to build the network request. This will fix an incorrect trailing slash on some requests.

Optimera - Adapter Update - Network Request Update

---

.gitignore

Adding package-lock.json to .gitignore file.

Adding package-lock.json to .gitignore.

---

pub-matic/DOCUMENTATION.md
pub-matic/pub-matic-htb-exports.js
pub-matic/pub-matic-htb-system-tests.js
pub-matic/pub-matic-htb-validator.js
pub-matic/pub-matic-htb.js

As chrome will only send third-party cookies over secure connections, pubmatic will make all requests over https.Also secure flag will be set to 1
Earlier in ortb request to PubMatic's endpoint we were passing eids as object which was an issue. Resolved this issue by converting eids from object to Array

Promoting PubMatic to Master: Changing protocol to HTTPS

---

gmsm/CHANGES.md
gmsm/DOCUMENTATION.md
gmsm/gmsm-htb-exports.js
gmsm/gmsm-htb-system-tests.js
gmsm/gmsm-htb-validator.js
gmsm/gmsm-htb.js
package-lock.json

- Initial creation of new GMSM adapter.
- Connects to AppNexus SSP, shares the same endpoint + code structure.
- Added support for upcoming `site` & `user` keyword objects to be passed by IX library.

[HTP-80] GMSM: New Adapter Creation.

---

colossus/CHANGES.md
colossus/DOCUMENTATION.md
colossus/colossus-htb-exports.js
colossus/colossus-htb-system-tests.js
colossus/colossus-htb-validator.js
colossus/colossus-htb.js

Page parameter should include only page path name not whole url

[HTP-0001] Colossus Adapter:  Get path instead of url

---

optimera/CHANGES.md
optimera/optimera-htb-system-tests.js
optimera/optimera-htb.js

Updates have been verified in canary, merging to master now.

[HTP-74] Optimera: Updating network request to use cloudfront, and use pathname.

---

colossus/CHANGES.md
colossus/DOCUMENTATION.md
colossus/colossus-htb-exports.js
colossus/colossus-htb-system-tests.js
colossus/colossus-htb-validator.js
colossus/colossus-htb.js

Updates have been verified in canary; this merges those changes into master, plus some documentation updates.

[HTP-90] Colossus: Get path instead of url

---

colossus/DOCUMENTATION.md

[HTP-0002] Colossus Adapter: Update Documentation.md

---

package-lock.json
undertone/CHANGES.md
undertone/DOCUMENTATION.md
undertone/undertone-htb-exports.js
undertone/undertone-htb-system-tests.js
undertone/undertone-htb-validator.js
undertone/undertone-htb.js

- Added GDPR module support that sends the consent information to Undertone API
- Added support for canonical url - if it exists and obtainable, it will be sent to udnertone API instead of full url
- Added support for external user id frameworks

[HTP-0001] Undertone Adapter: Adapter migration to new repo and new features

---

undertone/undertone-htb.js

Added handling a case when provider is not enabled, in this case we'll notify the server so it will decide how to handle

Undertone - GDPR - handle privacyEnabled=0

---

districtm-dmx/DOCUMENTATION.md
districtm-dmx/districtm-dmx-htb-system-tests.js
districtm-dmx/districtm-dmx-htb.js

Missing colon generate an http request on a secure page.
The side effect was: notification was blocked by the browser and giving us 30% of Google numbers.
- [x ] Bug Fix

Missing colon

---

gum-gum/CHANGES.md
gum-gum/DOCUMENTATION.md
gum-gum/gum-gum-htb-exports.js
gum-gum/gum-gum-htb-system-tests.js
gum-gum/gum-gum-htb-validator.js
gum-gum/gum-gum-htb.js

Migrates to new IX repo. adds a ns param and stringifies jcsi

Promote GumGum to production from canary

---

gum-gum/CHANGES.md
gum-gum/DOCUMENTATION.md
gum-gum/gum-gum-htb-exports.js
gum-gum/gum-gum-htb-system-tests.js
gum-gum/gum-gum-htb-validator.js
gum-gum/gum-gum-htb.js

Promote GumGum to production from canary
GumGum: Merge Master Into Canary
#

GumGum: Merge Master Into Canary

---

inskin-media/inskin-media-htb-system-tests.js
inskin-media/inskin-media-htb.js

Always pass through our demand as 1x1 in order to transact correctly in the publisher ad server.

[HTP-0117] Inskin Adapter: Pass demand as 1x1

---

kargo/CHANGES.md
kargo/DOCUMENTATION.md
kargo/kargo-htb-exports.js
kargo/kargo-htb-system-tests.js
kargo/kargo-htb-validator.js
kargo/kargo-htb.js

Kargo migrated to new repository as well as docs, tests, TDID update and localstorage additions. Should supersede #27 
Specifically, we are concerned about cookies in mobile iOS on account of Apple's recent ITP updates and have moved our products to use localstorage as canonical rather than cookies. This PR will make the adapter look at localstorage first before looking at cookies which will be more reliable in the long run on iOS devices.

[HTP-69] Kargo Adapter: Migration + updates

---

quantcast/CHANGES.md
quantcast/DOCUMENTATION.md
quantcast/quantcast-htb-exports.js
quantcast/quantcast-htb-system-tests.js
quantcast/quantcast-htb-validator.js
quantcast/quantcast-htb.js

Initial version of Quantcast adapter.

[HTP-65] Quantcast: New Adapter

---

piximedia/DOCUMENTATION.md
piximedia/piximedia-htb-exports.js
piximedia/piximedia-htb-system-tests.js
piximedia/piximedia-htb-validator.js
piximedia/piximedia-htb.js

As we discussed by email with Khushi, this is the PR to add the Piximedia adapter.

Piximedia Adapter: Add Adapter

---

aja/DOCUMENTATION.md
aja/aja-htb-exports.js
aja/aja-htb-system-tests.js
aja/aja-htb-validator.js
aja/aja-htb.js

[HTP-0001] aja adaptor

---

app-nexus-network/CHANGES.md
app-nexus-network/DOCUMENTATION.md
app-nexus-network/app-nexus-network-htb-exports.js
app-nexus-network/app-nexus-network-htb-system-tests.js
app-nexus-network/app-nexus-network-htb-validator.js
app-nexus-network/app-nexus-network-htb.js

Update the adapter to use a new endpoint and allow supported for some new bidder fields.

[HTP-0002] app-nexus-network: update endpoint

---

gum-gum/CHANGES.md
gum-gum/gum-gum-htb.js

Adds support for ccpa/us privacy using IX's `ComplianceService.usp.getConsent()` function

[HTP-107] GumGum: Adds CCPA Support

---

quantcast/CHANGES.md
quantcast/quantcast-htb-system-tests.js
quantcast/quantcast-htb.js

Pass CCPA data in bid request to QC adapter.

[HTP-111] Quantcast: Add CCPA to bid request

---

locker-dome/CHANGES.md
locker-dome/DOCUMENTATION.md
locker-dome/locker-dome-htb.js

Add CCPA/USP support for the LockerDome adapter
https://jira.indexexchange.com/servicedesk/customer/portal/15/HTP-109

[HTP-109] LockerDome: Add CCPA/USP support

---

open-x/CHANGES.md
open-x/DOCUMENTATION.md
open-x/open-x-htb-exports.js
open-x/open-x-htb-system-tests.js
open-x/open-x-htb-validator.js
open-x/open-x-htb.js

As requested, this PR is a copy of the current adapter located at https://github.com/indexexchange/open-x-adapter into the mono-repo.
I have also made a PR to the old repo with the exact changes to make understanding the changes easier -> https://github.com/indexexchange/open-x-adapter/pull/6
Features included:
CCPA/USP support. This PR also changes all ad request calls to HTTPS to prepare for SameSite changes.

[HTP-103] OpenX: CCPA/USP support and force HTTPS calls

---

gum-gum/CHANGES.md
gum-gum/gum-gum-htb.js

GumGum: Adds CCPA Support

---

open-x/CHANGES.md
open-x/DOCUMENTATION.md
open-x/open-x-htb-exports.js
open-x/open-x-htb-system-tests.js
open-x/open-x-htb-validator.js
open-x/open-x-htb.js

As requested, this PR is a copy of the current adapter located at https://github.com/indexexchange/open-x-adapter into the mono-repo.
I have also made a PR to the old repo with the exact changes to make understanding the changes easier -> indexexchange/open-x-adapter#6
Features included:
CCPA/USP support. This PR also changes all ad request calls to HTTPS to prepare for SameSite changes.

OpenX: CCPA/USP support and force HTTPS calls

---

locker-dome/CHANGES.md
locker-dome/DOCUMENTATION.md
locker-dome/locker-dome-htb.js

Add CCPA/USP support for the LockerDome adapter
https://jira.indexexchange.com/servicedesk/customer/portal/15/HTP-109

Lockerdome ccpa

---

.eslintignore
app-nexus/CHANGES.md
app-nexus/DOCUMENTATION.md
app-nexus/app-nexus-htb-exports.js
app-nexus/app-nexus-htb-system-tests.js
app-nexus/app-nexus-htb-validator.js
app-nexus/app-nexus-htb.js

Per the request made [here](https://github.com/indexexchange/ix-library-adapters/pull/52#discussion_r360434835), I have created a new PR using the original version of our app-nexus bidder in order to add CCPA support.
Please let me know if anything further is needed.

[HTP-0004] app-nexus: add original app-nexus bidder with ccpa support

---

rubicon/CHANGES.md
rubicon/rubicon-htb.js

rubicon adapter: change p_pos default

---

rubicon/CHANGES.md
rubicon/rubicon-htb.js

This reverts commit f44baaca0d006a74792997c3da01e9e002f765e9, reversing
changes made to 71bc1867d9854f93ab8ced52d56b60fc28298c68.
#

Revert "Merge pull request #155 from rubicon-project/master"

---

kargo/CHANGES.md
kargo/DOCUMENTATION.md
kargo/kargo-htb-system-tests.js
kargo/kargo-htb.js

[HTP-115] Kargo support for IAB US privacy string

---

trust-x/CHANGES.md
trust-x/DOCUMENTATION.md
trust-x/trust-x-htb.js

Added CCPA support in TrustX bid adapter

[HTP-114]TrustX: Add CCPA support

---

rubicon/CHANGES.md
rubicon/rubicon-htb.js

Reverts indexexchange/ix-library-adapters#157

Revert "Revert "Merge pull request #155 from rubicon-project/master""

---

share-through/CHANGES.md
share-through/DOCUMENTATION.md
share-through/share-through-htb-system-tests.js
share-through/share-through-htb.js

- Sharethrough bid adapter endpoint has been updated to always use `https`
- Protocol of the referrer is now sent as an additional parameter in bid requests
#

[HTP-106] Sharethrough: Update bid adapter endpoint

---

.eslintignore
triple-lift/CHANGES.md
triple-lift/DOCUMENTATION.md
triple-lift/triple-lift-htb-exports.js
triple-lift/triple-lift-htb-system-tests.js
triple-lift/triple-lift-htb-validator.js
triple-lift/triple-lift-htb.js

- Migrates TripleLift adapter from [here](https://github.com/indexexchange/triple-lift-adapter)
- Adds system tests
- Adds tmax query param to auction request
- Adds CCPA query param to auction request
- Hardcodes HTTPS protocol for auction request

[HTP-68] TripleLift adapter and tmax/CCPA updates

---

aja/aja-htb-system-tests.js
aja/aja-htb.js

[HTP-120] AJA: updates bidUnitInCents

---

emx-digital/CHANGES.md
emx-digital/emx-digital-htb-system-tests.js
emx-digital/emx-digital-htb.js

* Add US CCPA Support
* fix tests
* target ccpa string
#

EMX: Add CCPA Suport (#147)

---

teads/DOCUMENTATION.md
teads/teads-htb-exports.js
teads/teads-htb-system-tests.js
teads/teads-htb-validator.js
teads/teads-htb.js

Introduce Teads adapter
For more information ping us 
Email to contact the team: innov-ssp@teads.tv

[HTP-0001]Introduce Teads adapter

---

aja/aja-htb-system-tests.js
aja/aja-htb.js
emx-digital/CHANGES.md
emx-digital/emx-digital-htb-system-tests.js
emx-digital/emx-digital-htb.js
teads/DOCUMENTATION.md
teads/teads-htb-exports.js
teads/teads-htb-system-tests.js
teads/teads-htb-validator.js
teads/teads-htb.js

sync canary

---

.eslintignore
rtk/CHANGES.md
rtk/DOCUMENTATION.md
rtk/rtk-htb-exports.js
rtk/rtk-htb-system-tests.js
rtk/rtk-htb-validator.js
rtk/rtk-htb.js

Add CCPA support for RTK aardvark bidder.

RTK: add CCPA support 

---

brightcom/CHANGES.md
brightcom/DOCUMENTATION.md
brightcom/brightcom-htb-exports.js
brightcom/brightcom-htb-system-tests.js
brightcom/brightcom-htb-validator.js
brightcom/brightcom-htb.js

Initial version - implementation of Brightcom Adapter.

[HTP-0001] Brightcom Adapter: New Adapter

---

app-nexus/CHANGES.md
app-nexus/DOCUMENTATION.md
app-nexus/app-nexus-htb-exports.js
app-nexus/app-nexus-htb-system-tests.js
app-nexus/app-nexus-htb-validator.js
app-nexus/app-nexus-htb.js

Semi-replacement of https://github.com/indexexchange/ix-library-adapters/pull/52
This PR updates the endpoint of the app-nexus bidder, which would allow it to support some additional publisher fields - such as `keywords`, `usePaymentRule` and `allowSmallerSizes`.

[HTP-0005] app-nexus: update endpoint and other changes

---

share-through/CHANGES.md
share-through/DOCUMENTATION.md
share-through/share-through-htb-system-tests.js
share-through/share-through-htb.js

Sharethrough's adapter will now consume the CCPA privacy signal from IX, if present.

[HTP-127] Sharethrough: Consume CCPA privacy signals

---

thirty-three-across/CHANGES.md
thirty-three-across/DOCUMENTATION.md
thirty-three-across/thirty-three-across-htb-exports.js
thirty-three-across/thirty-three-across-htb-system-tests.js
thirty-three-across/thirty-three-across-htb-validator.js
thirty-three-across/thirty-three-across-htb.js

Initial adapter implementation

[HTP-132] 33Across Adapter: New Certification

---

trust-x/CHANGES.md
trust-x/trust-x-htb.js

Update TrustX Adapter to Access CCPA Consent Data

[HTP-133]TrustX: Update Access CCPA Consent Data

---

trust-x/CHANGES.md
trust-x/trust-x-htb.js

Promote TrustX CCPA Update From Canary to Production

Promote TrustX CCPA Update From Canary to Production

---

README.md
aol/CHANGES.md
aol/DOCUMENTATION.md
aol/aol-htb-exports.js
aol/aol-htb-system-tests.js
aol/aol-htb-validator.js
aol/aol-htb.js
app-nexus/CHANGES.md
app-nexus/DOCUMENTATION.md
app-nexus/app-nexus-htb-exports.js
app-nexus/app-nexus-htb-system-tests.js
app-nexus/app-nexus-htb-validator.js
app-nexus/app-nexus-htb.js
oath/CHANGES.md
oath/DOCUMENTATION.md
oath/oath-htb-exports.js
oath/oath-htb-system-tests.js
oath/oath-htb-validator.js
oath/oath-htb.js
trust-x/CHANGES.md
trust-x/trust-x-htb.js

master to canary

---

just-premium/just-premium-htb.js

JustPremium: Add support for ccpa

---

thirty-three-across/CHANGES.md
thirty-three-across/thirty-three-across-htb-system-tests.js
thirty-three-across/thirty-three-across-htb-validator.js
thirty-three-across/thirty-three-across-htb.js

* fix the site id validation
* update changelog
* update the adapter version
#

[HTP-0001] 33Across Adapter: Fix Validation (#206)

---

ad-you-like/CHANGES.md
ad-you-like/DOCUMENTATION.md
ad-you-like/ad-you-like-htb-exports.js
ad-you-like/ad-you-like-htb-system-tests.js
ad-you-like/ad-you-like-htb-validator.js
ad-you-like/ad-you-like-htb.js

Create new AdYouLike bidding adapter 
Please note that the link to guideline in default PR description is outdated:
https://knowledgebase.indexexchange.com/display/ADAPTER/Adapter+Code+Submission+Guidelines

"[HTP-0001]  AdYouLike adaptor : create adaptor

---

concert/CHANGES.md
concert/DOCUMENTATION.md
concert/concert-htb-exports.js
concert/concert-htb-system-tests.js
concert/concert-htb-validator.js
concert/concert-htb.js

New IX adapter, for Concert ad network.

Add concert bid adapter

---

kargo/CHANGES.md
kargo/DOCUMENTATION.md
kargo/kargo-htb-system-tests.js
kargo/kargo-htb.js

Support Liveramp IDL Envelope
Support GDPR

[HTP-1000] Kargo Adapter: Support Liveramp IDL Envelope and GDPR

---

kargo/CHANGES.md
kargo/DOCUMENTATION.md
kargo/kargo-htb-system-tests.js
kargo/kargo-htb.js

Kargo Adapter: Support Liveramp IDL Envelope and GDPR to Prod

---

no-bid/no-bid-htb-validator.js
no-bid/no-bid-htb.js

Added support for optional parameter: Placement ID.

[HTP-0001] NoBid: Added Placement ID support

---

concert/CHANGES.md
concert/concert-htb-system-tests.js
concert/concert-htb.js

Update bidUnitInCents to return bids in dollars
#

[HTP-0001] Concert: Update bidUnitInCents to return bids in dollars

---

just-premium/just-premium-htb.js

Pass page url in request object.

JustPremium - pass page url
